### ISSUE TITLE
Tests and quizzes

### ISSUE THREAD

**Issue by danirod** [makigas/makigas#49]
This is a marking ID for this feature. A quiz allows the user or viewer to test their knowledge based on what he/she recently learnt. Cool idea proposed by @juanteran in #5.

Implementation details to set:

* Integrate tests on the makigas/makigas source code or make it a different software project?
* Only an admin can create quizzes or let the community create new quizzes?
* (To be continued?)

**Comment by juanteran** [comment]
Few comment on this, weird, thanks for the mention, had time without going through github.

Regarding what you mention from whom to create the exams, I would like it to be you (more work for @danirod  hahahaha) for the simple fact of being the instructor and knowing how to evaluate what has been learned.

You can do the tests per level as they go forward or just leave it as a final exam, such as when you finish the semester xD.
