### ISSUE TITLE
Transcriptions

### ISSUE THREAD

**Issue by danirod** [makigas/makigas#5]
This is a tracking issue for transcriptions. **Transcriptions** are alternative text representations of the content of a video that are displayed in the same page as the video or in a different page but linked to the video so that it is possible to view it.

**This is not the same as subtitles**. Subtitles are uploaded to the video and provide an alternate representation of the speech said in the video, and an alternate representation of other sound effects in case its closed captioned. However, transcriptions are rich text documents. They may use extra formatting, they may add code, and they may not include the textual representation of the audio layer for a video.

The following cases are presented:

* **Transcriptions allow to paste code snippets that are presented through the video**. This allows viewers that want to test the example code to copy and paste it. Not every chunk of code should be added as a transcription.
* Transcriptions provide **accessibility alternatives** in the cases the video content cannot be properly viewed by people with dissabilities such as deafness or hearing impairments.
* Transcriptions allows users that don't want to watch the entire video to get an overview on what happens there to decide whether to play it or not.
* Transcriptions may allow search engines to better understand the contents of a video in order to include the page in the search results for particular queries that are related to the content of the video.

**Comment by juanteran** [comment]
The idea that you propose is very interesting, however, the subtitulos you could also add them, use your community to help you transcribe if you want.

Hey, i can not answer your questions in Spanish or yes?

**Comment by danirod** [comment]
> El 4 jul 2017, a las 19:49, Juan Carlos Terán <notifications@github.com> escribió:
> 
> The idea that you propose is very interesting, however, the subtitulos you could also add them, use your community to help you transcribe if you want.
> 
> Hey, i can not answer your questions in Spanish or yes?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Cualquiera de los dos idiomas vale, el idioma por defecto es el inglés por costumbre pero me es indiferente.

Tengo activos los subtítulos de la comunidad para muchos vídeos, es una opción que se configura a través de YouTube. En muchos de los vídeos al pulsar el botón “Subtítulos” en el player de youtube.com aparece una opción llamada Añadir subtítulos que permite crear transcripciones de la comunidad. No le he dado mucha difusión nunca realmente, porque no entiendo cómo funciona el proceso de revisión, pero ahí está.

No obstante, la transcripción de la web es ligeramente distinta al subtitulado de los vídeos. Lo que quiero hacer aquí es incorporar texto con formato, por ejemplo los fragmentos de código que se ven en el vídeo o enlaces. Como lo que hacen en [Vimcasts](http://vimcasts.org/episodes/ultisnips-visual-placeholder/), que no es que te pongan las frases línea a línea sino que tiene formato de artículo por si no quieres ver el vídeo pero quieres localizar una frase concreta para una cosa que necesitas.

--
Dani Rodríguez <dani@danirod.es>
PGP Signature: 0C1A 97B5 330D 653A 4470 1E6D E787 7B8C 964C 8E61
Web site: https://www.danirod.es – Twitter: @danirod93

**Comment by juanteran** [comment]
Entiendo, mostrar en el contexto el las frases o el contenido más destacado en el video. Tu idea es muy buena y educativa en cierto modo, ayuda en el aprendizaje o aquel que solo desea repasar de manera rápida en su smartphone. Y mucha utilidad.

Quería comentarte algo que podrías agregar a makigas es una especie de Examenes o Pruebas al final de cada curso para demostrar lo aprendido, (no es obligatoriamente a el final, puede ser incluso a mitad de un curso), así  ejercita a el estudiante :D.

**Comment by danirod** [comment]
Le he asignado a esta propuesta un issue independiente por si en algún momento me animo a llevarla a cabo. Es una buena idea, la verdad.
