### ISSUE TITLE
Images AccessDenied

### ISSUE THREAD

**Issue by roboto-cloud** [makigas/makigas#83]
Hi @danirod :)
Not images available using docker. the URL get this message:
you know how fix it?
thanks in advance,

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key/>
<BucketName/>
<Resource>
/makigas/playlists/thumbnails/000/000/001/small/main-00.jpg
</Resource>
<RequestId>3L137</RequestId>
<HostId>3L137</HostId>
</Error>
```

**Comment by danirod** [comment]
This bug has finally been fixed by adding a Rake task that manually sets up the bucket policy for the container storing the application assets. This Rake task is automatically executed inside the Docker container unless told otherwise.

Will be merged soon.
