### ISSUE TITLE
El boton de survey para sugerir articulos no funciona?

### ISSUE THREAD

**Issue by Klairm** [makigas/makigas#874]
He intentado darle al boton de "Si" donde pregunta si seria util un articulo de un video en la web, y parece no hacer nada? No se si falta un onSubmit o algo por el estilo, o si que hace algo pero en la interfaz no parece que ocurra nada.

Adjunto gif:

![Peek 2024-11-01 17-07](https://github.com/user-attachments/assets/481b2da7-462f-4b57-94cb-24c5a56f94cb)

**Comment by danirod** [comment]
Parece que se registra el evento pero no actualiza el texto del botón. Gracias por el aviso.

**Comment by danirod** [comment]
Vaya, sé que se registra porque tengo 37 eventos metidos hoy en la página sobre [Fusiones conflictivas](https://www.makigas.es/series/tutorial-de-git/fusiones-conflictivas) xD

![image](https://github.com/user-attachments/assets/eb47f30d-7b5a-4950-8acd-2e7945777841)

**Comment by Klairm** [comment]
> Vaya, sé que se registra porque tengo 37 eventos metidos hoy en la página sobre [Fusiones conflictivas](https://www.makigas.es/series/tutorial-de-git/fusiones-conflictivas) xD
> 
> ![image](https://private-user-images.githubusercontent.com/1568690/382358523-eb47f30d-7b5a-4950-8acd-2e7945777841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODI5MzEsIm5iZiI6MTczMDQ4MjYzMSwicGF0aCI6Ii8xNTY4NjkwLzM4MjM1ODUyMy1lYjQ3ZjMwZC03YjVhLTQ5NTAtOGFjZC0yZTc5NDU3Nzc4NDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMTczNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhiOGU5OGE5ZDkxOWEwMTBlZDY2NDEwMjNkN2NlYjViM2MwMGI2YzJkMGQxNzJkMDIzY2YyZGE5MTA4NGQyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jUeCHQljCQ2LqAmE-ZGQJP03vNoH7vKaJhyjX_wNd5c)

aksjakjskajs pido perdon, me parecia raro, entonces es algo visual solo

**Comment by danirod** [comment]
Cambio que arregla esto incorporado en commit e8c13318422b20c5c17c166b8459bce34aa07d01.
Desplegado a producción en la run [`12131342279`](https://github.com/makigas/makigas.es/actions/runs/12131342279).
